export const TERMS_AND_CONDITIONS = `THIS TERMS OF USE AGREEMENT (THE "AGREEMENT") ESTABLISHES THE TERMS AND CONDITIONS THAT APPLY TO YOU WHEN YOU USE THE SERVICE (AS DEFINED BELOW). BY USING THE SERVICE, YOU INDICATE YOUR ACCEPTANCE OF THIS AGREEMENT AND YOUR AGREEMENT TO BE BOUND BY THE TERMS AND CONDITIONS OF THIS AGREEMENT, AS WELL AS ALL APPLICABLE LAWS AND REGULATIONS. YOU ARE NOT PERMITTED TO USE THE SERVICE IF YOU DO NOT AGREE TO ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT. THIS AGREEMENT CAN BE CHANGED, MODIFIED, SUPPLEMENTED, AND/OR UPDATED BY SLIMiot Private Limited. ("THE COMPANY", "WE", "OUR"," OR "US") AT ANY TIME; PROVIDED THAT WE WILL PUBLISH PRIOR NOTICE OF ANY MATERIAL CHANGES. YOUR CONTINUED USE OF THE SERVICE AFTER THE MODIFICATION OF THIS AGREEMENT MEANS THAT YOU ACCEPT ALL SUCH CHANGES. ACCORDINGLY, YOU ARE ADVISED TO CONSULT THIS AGREEMENT EACH TIME YOU ACCESS THE SERVICE IN ORDER TO VIEW ANY CHANGES TO THIS AGREEMENT. THIS AGREEMENT WAS LAST MODIFIED AS OF THE DATE INDICATED ABOVE.

1. Use of Web Site, Mobile Applications, and our Service
a.The "Service" is SLIMiot's mobile applications and website located at slimiot.com , as each may be updated, relocated, or otherwise modified from time to time, including through networks, embeddable widgets, downloadable software, and tablet computer applications, and all intellectual property contained therein. The Service provides a GPS-GSM device allowing you to find and track the device with a network through which Slimiot can provide locations (each, a "Location") to consumers. Any person who accesses and/or uses the Slimiot Network to locate a device on his or her own behalf, or on behalf of any third party, will be referred to herein as a ("SLIMiot Member").

b. The “Service” is also SLIMiot’s IOT devices, proprietary or otherwise, wearable or otherwise used to collect wellness and lifestyle data of its users for the sole purpose of analysis and as deemed fit by the company.
b. Subject to the terms and conditions of this Agreement, THE COMPANY hereby grants you a limited revocable, non-exclusive, non-transferable license to access and use the Service, solely in the manner intended by THE COMPANY. Unless otherwise specified in writing, the Service is solely for your personal use and not for resale. THE COMPANY reserves the right at all times and without notice to: (i) restrict and/or terminate your access to the Service (or any portion thereof); and (ii) modify or discontinue providing the Service (or any portion thereof).

c. THE COMPANY’s policy with respect to the collection and use of your personally identifiable information is set in our Privacy Policy. By accepting this Agreement, you acknowledge your agreement with SLIMiot’s Privacy Policy.

2. Registration, Accounts, Passwords and Security
a. SLIMiot Members. In order to become a SLIMiot Member, you must complete the registration process by providing THE COMPANY with current, complete and accurate information, as prompted by the applicable registration form.

b. Accuracy of Information. You acknowledge that in the event you provide any information to THE COMPANY which is untrue, inaccurate, not current or incomplete, THE COMPANY may terminate this Agreement and your continued access and use of the Service.

c. Eligibility. You represent and warrant that you are at least eighteen (18) years of age, that you have not been previously suspended or removed from the Service, and that you possess the legal right and ability to enter into this Agreement. If you are using the Service on behalf of an individual, company, entity, or organization, you represent and warrant that you are an authorized representative of such party with the authority to (i) bind such party to this Agreement, and (ii) agree to be bound by the Agreement on behalf of such party. THE SERVICE IS NOT FOR PERSONS UNDER THE AGE OF 13 OR ANY USERS PREVIOUSLY SUSPENDED OR REMOVED FROM THE SERVICE BY THE COMPANY. IF YOU ARE UNDER 13 YEARS OF AGE, PLEASE DO NOT USE OR ACCESS THE SERVICE AT ANY TIME OR IN ANY MANNER. While individuals under the age of 18 may use the SLIMiot services through the Service by a parent or legal guardian (who must also supervise theSLIMiot device), such individuals may not use the Service themselves.

d. Credentials. As part of the registration process, you will be asked to select a username and password. You are entirely responsible for maintaining the security and confidentiality of your account’s identification details and password. You agree to notify THE COMPANY immediately of any unauthorized use of your account or any other breach of security. To notify us, contact us at info@SLIMiot.com You are responsible for all use of the Service occurring under your user name. You are responsible for keeping your password confidential and for notifying us if your password has been hacked or stolen. THE COMPANY will not be liable for any loss that you may incur as a result of someone else using your password or account, either with or without your knowledge. You may be held liable for any losses incurred by THE COMPANY or another party due to someone else using your account or password.

3. Your Responsibilities
a. You may use the Service solely for lawful, non-commercial purposes, as intended through the provided functionality of the Service. You may not use the Service in any manner that could damage, disable, overburden, or impair our servers or networks, or interfere with any other party’s use and enjoyment of the Service. You may not attempt to gain unauthorized access to the Service, user accounts, or computer systems or networks, through hacking, password mining or any other means. Without limiting any of the foregoing, you expressly agree that you will not (and you agree not to allow or assist any third party to):

i. use, copy, install, transfer or distribute the Service, except as specifically permitted by this Agreement;

ii. modify, adapt, translate, reverse engineer, decompile, or disassemble any portion of the Service or its Content (as defined below);

iii. remove or alter any copyright, trademark or other proprietary rights notices contained in or on the Service or in or on any content or other material obtained through the Service or the use of the Service;

iv. create user accounts by automated means or under false or fraudulent pretenses;

v. use any robot, spider, screen or database scraper, site search or retrieval application, or other automated device, process or means to access, retrieve or index any portion of the Service;

vi. probe, scan or test the vulnerability of any system or network or breach any security or authentication measures;

vii. reformat, mirror, or frame any portion of the web pages that are part of the Service;

viii. reformat, mirror, or frame any portion of the web pages that are part of the Service;

ix. transmit (A) any content or information that is unlawful, fraudulent, threatening, abusive, libelous, defamatory, obscene or otherwise objectionable, or infringes on our or any third party’s intellectual property or other rights, (B) any material, non- public information about individuals or companies without the authorization to do so, (C) any trade secret of any third party, and/or (D) any advertisements, solicitations, chain letters, pyramid schemes, investment opportunities, or other unsolicited commercial communication (except as otherwise expressly permitted by us), or engage in spamming or flooding;

x. transmit any software or other materials that contain any virus, worm, time bomb, Trojan horse, or other harmful or disruptive component; use any robot, spider, site search/retrieval application, or other manual or automatic device or process to retrieve, index, “data mine”, or in any way reproduce or circumvent the navigational structure or presentation of the Service or its contents;

xi. harvest or collect information about other users without their prior written consent; xii. undertake, cause, permit or authorize the translation, reverse engineering, disassembling or hacking of any aspect of the Service, including Content, or attempt to do any of the foregoing, except and solely to the extent permitted by this Agreement, the Service’s authorized features, or by law, or otherwise attempt to use or access any portion of the Service other than as intended by THE COMPANY;

xiii. access, tamper with, or use non-public areas of the Service, THE COMPANY’s (and its hosting company’s) computer systems and infrastructure, or the technical delivery systems of THE COMPANY’s providers;

xiv. harass, abuse, harm or advocate or incite harassment, abuse or harm of another person or group, including THE COMPANY employees and other users;

xv. create a new account with SLIMiot, without THE COMPANY’s express written consent, if THE COMPANY previously disabled an account of yours;

xvi. solicit, or attempt to solicit, personal information from other users, except as permitted through the Service’s functionality;

xvii. restrict, discourage or inhibit any person from using the Service, disclose personal information about a third person on the Service or obtained from the Service without the consent of such person, or collect information about users;

xviii. gain unauthorized access to the Service, to other users’ accounts, names or personally identifiable information, or to other computers or websites connected or linked to the Service;

xix. violate any applicable federal, state or local laws, regulations or this Agreement;

xx. use the Service for any illegal, inappropriate and/or unauthorized conduct, including without limitation, using the Service in violation of THE COMPANY’s or any third party’s intellectual property or other proprietary or legal rights; or

xxi. use or access the Service to build a competing service.We may take any legal action and implement any technical remedies to prevent the violation of these provisions and to enforce this Agreement.

4. Consent to Electronic Communications
a. Consent to Electronic Communications. By using the Service or providing Personal Information (as defined in the Privacy Policy) to us, you agree that we may communicate with you electronically regarding security, privacy, and administrative issues relating to your use of the Service. If we learn of a security system’s breach, we may attempt to notify you electronically by posting a notice on the Service or sending an email to you, if we have your email address. You may have a legal right to receive this notice in writing. To receive free written notice of a security breach (or to withdraw your consent from receiving electronic notice), please write to us at info@SLIMiot.com.

b. SMS Text Messages and Push Notifications. When you register with SLIMiot, THE COMPANY may send you an SMS text message containing a 4-digit code in order to verify your phone number and may send SMS text messages and push notifications (“Messages and Notifications”) in order to keep you informed about the Service, and may present to you certain marketing offers related to the service. By using the Service, you agree to receive Messages and Notifications regarding your use of the Service. SMS text messages are for informational purposes only. While Messages and Notifications are intended to enhance your use of the Service, you may (i) disable push notifications on your device to remove yourself from our text message database.

c. THE COMPANY cannot control certain factors relating to message delivery. You acknowledge that, depending on your mobile carrier’s service, it may not be possible to transmit a text message to you successfully. We have no liability for transmission delays or message failures.

5. Content Submitted to THE COMPANY
a. By sending or transmitting to us information, opinions, creative suggestions, ideas, notes, concepts, or other materials (collectively, “Materials”), or by posting such Materials to any area of the Service, you grant THE COMPANY and its designees a worldwide, non-exclusive, sublicenseable (through multiple tiers), assignable, royalty-free, perpetual, irrevocable right to use, reproduce, distribute (through multiple tiers), create derivative works of, publicly perform, publicly display, digitally perform, make, have made, sell, offer for sale and import such Materials in any media now known or hereafter developed to enhance and develop the Service, including by marketing and advertising the Service, without compensation to you; provided that we will never use your name in connection with any of your Materials that we use in our own advertising and marketing materials without obtaining your prior consent. None of the Materials will be subject to any obligation, whether of confidentiality, attribution, or otherwise, on our part and we will not be liable for any use or disclosure of any Materials. THE COMPANY may remove or alter any Materials at any time for any reason. We neither endorse nor are responsible for any opinion, advice, information, or statement made or displayed on the Service by any user. We are not responsible for any errors or omissions in articles or postings, for hyperlinks embedded in messages, or for any results obtained from the use of such information. Under no circumstances will THE COMPANY and/or its affiliates, suppliers, or agents be liable for any loss or damage caused by your reliance on such information obtained through the Service. We cannot and do not take responsibility for the veracity, reliability, or completeness of any opinion, advice, information, or statement available on the Service.

b. The opinions expressed on the Service by users reflect solely the opinions of the users who post thereon and do not reflect the opinions of THE COMPANY. You acknowledge and agree that we have the right (but not the obligation) to monitor the Service and Materials; to alter or remove any Materials; and to disclose Materials and the circumstances surrounding their transmission to any third party in order to operate the Service properly; to protect ourselves, our sponsors, and our members and visitors; and to comply with legal obligations or governmental requests. If you believe a message violates our member policies, please contact THE COMPANY immediatelyso that we can consider its editing or removal.

c. You are solely responsible for your Materials and the consequences of posting them on the Service. By posting Materials, you represent, warrant, and covenant that:
(i) you are the creator and owner of the Materials or otherwise have sufficient rights and authority to grant the rights granted herein;
(ii) your Materials do not and will not (A) infringe, violate, or misappropriate any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right or (B) slander, defame, or libel any other person;
(iii) your Materials do not contain any viruses, adware, spyware, worms, or other harmful or malicious code or
(iv) unless you have received prior written authorization, your Materials specifically do not contain any confidential information of any third party. We reserve all rights and remedies against any users who breach these representations and warranties.

6. Term and Termination
a. Term. The term of this Agreement (the “Term”) will commence on the date on which you first access or utilize the Service in any way (the “Effective Date”) and will continue so long as you continue to access or utilize the Service; provided that THE COMPANY reserves the right to take whatever lawful actions it may deem appropriate in response to actual or suspected violations of this Agreement including, without limitation, the suspension or termination of the user’s access and/or account, or blocking the user from access to the Service. THE COMPANY may cooperate with legal authorities and/or third parties in the investigation of any suspected or alleged crime or civil wrong. Except as may be expressly limited by the Privacy Policy, THE COMPANY reserves the right at all times to disclose any information as THE COMPANY deems necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in THE COMPANY’s sole discretion.

b. Effect of Termination. The following Sections of this Agreement will survive termination or expiration of the Agreement: 1.c, 2.d, 3, 4, 5.e, 7.a, 8, 10.b, 11, 12, 13, 14, 15, 16, 17, 19 – 27. Payments by you, which accrue or are due before termination of your contract, will continue to be payable by you, and amounts owed to THE COMPANY at the time of such termination or expiration will continue to be owed by you, after such expiration or termination.

7. Ownership
a. Proprietary Information. You acknowledge and agree that:
(i) the Service, including, without limitation, any Content, modifications, enhancements and updates, and any originals and copies thereof, in whole or in part, and all intellectual property rights therein (collectively, “Proprietary Information”), is owned by THE COMPANY and its licensors, as applicable;
(ii) the Proprietary Information contains valuable copyrighted and proprietary material of THE COMPANY;
(iii) the Proprietary Information is licensed, rather than sold, to you pursuant to this Agreement; and
(iv) you have no rights in the Proprietary Information, other than the rights and licenses specifically granted to you pursuant to this Agreement.

b. Trademarks. You acknowledge that THE COMPANY has acquired, and is the owner of, trademark rights in the name and word mark “SLIMiot”™ and in the other marks and design marks displayed on the Service. You acknowledge that this name and these marks are famous and internationally known. You will not, at any time or for any reason, challenge the validity of, or THE COMPANY’s ownership of, the foregoing name and marks, and you waive any rights you may have at any time to do so. All use of the foregoing name and marks by you will inure exclusively to the benefit of THE COMPANY. All marks shown on the Service but not owned by THE COMPANY are the property of their respective owners.

8. Claims of Copyright Infringement.
The Copyright (Amendment) Act 2012 provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under Indian copyright law. If you believe in good faith that materials hosted by THE COMPANY infringe your copyright, you (or your agent) may send us a notice requesting that the material be removed, or access to it blocked. The notice must include the following information:

a. a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;

b. identification of the copyrighted work claimed to have been infringed (or if multiple copyrighted works located on the Service are covered by a single notification, a representative list of such works);

c. identification of the material that is claimed to be infringing or the subject of infringing activity, and information reasonably sufficient to allow THE COMPANY to locate the material on the Service;

d. the name, address, telephone number, and email address (if available) of the complaining party;

e. a statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and

f. a statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.

If you believe in good faith that a notice of copyright infringement has been wrongly filed against you, the authority permits you to send THE COMPANY a counter-notice. Notices and counter-notices must meet the then-current statutory requirements imposed by the authority; see http://copyright.gov.in/ for details. Notices and counter- notices with respect to the Service should be sent to, Slimiot Private Limited. at address: 429, Sector 11D, Faridabad, Haryana, India. We suggest that you consult your legal advisor before filing a notice or counter-notice. Also, be aware that there can be penalties for false claims.

9. Disclaimer of Warranty.
a. THE SERVICE IS PROVIDED “AS IS” WITH ALL FAULTS, AND THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND EFFORT IS WITH YOU. YOU ACKNOWLEDGE THAT, BECAUSE OF THE NATURE OF THE INTERNET, MOBILE NETWORKS, AND THE DEVICES WHICH ACCESS THE INTERNET AND/OR MOBILE NETWORKS, THE SERVICE MAY NOT BE ACCESSIBLE WHEN NEEDED, AND THAT INFORMATION, DATA, AUDIO AND VIDEO TRANSMITTED OVER THE INTERNET AND/OR MOBILE NETWORKS MAY BE SUBJECT TO INTERRUPTION OR THIRD PARTY INTERCEPTION AND MODIFICATION. THE COMPANY DISCLAIMS ANY AND ALL WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT, ACCURACY OF INFORMATIONAL CONTENT, AND ABSENCE OF VIRUSES AND DAMAGING OR DISABLING CODE. NONE OF THE COMPANY, ITS AFFILIATES OR SERVICE PROVIDERS, THE COMPANY’S CONTENT PROVIDERS AND/OR THEIR RESPECTIVE AFFILIATES, SUBSIDIARIES NOR THE EMPLOYEES, AGENTS AND/OR CONTRACTORS (COLLECTIVELY, THE “SLIMIOT PARTIES”) WARRANT THE ACCURACY, COMPLETENESS, OR TIMELINESS OF THE SERVICE. THE COMPANY CANNOT AND DOES NOT ASSUME ANY RESPONSIBILITY FOR ANY LOSS, DAMAGES OR LIABILITIES ARISING FROM THE FAILURE OF ANY TELECOMMUNICATIONS INFRASTRUCTURE, OR THE INTERNET OR FOR YOUR MISUSE OF ANY OF CONTENT AND INFORMATION ACCESSED THROUGH THE SERVICE. YOU EXPRESSLY AGREE THAT YOUR USE OF THE SERVICE AND YOUR RELIANCE UPON ANY OF THE RESPECTIVE CONTENT IS AT YOUR SOLE RISK.

10. Limitation of Liability.
a. EACH USER IS SOLELY RESPONSIBLE FOR (I) HIS OR HER USE OF THE SERVICE, AND (II) ANY DAMAGES INCURRED BY HIM OR HER OR ANY THIRD PARTY THAT ARISE FROM OR ARE RELATED TO THE SERVICE. THE AGGREGATE LIABILITY OF THE SLIMIOT PARTIES FOR ANY DAMAGES, WHETHER ARISING IN CONTRACT, TORT OR OTHERWISE, WILL BE LIMITED TO ACTUAL DAMAGES PROVED, AND NOT TO EXCEED THE AMOUNT PAID BY YOU TO THE COMPANY FOR THE SERVICE. NOTWITHSTANDING ANYTHING TO THE CONTRARY SET FORTH HEREIN, NONE OF THE SLIMIOT PARTIES WILL BE LIABLE FOR ANY PUNITIVE, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES, EVEN IF THE COMPANY OR ITS CONTENT PROVIDERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

b. NONE OF THE SLIMIOT PARTIES WILL HAVE ANY LIABILITY WHATSOEVER FOR ANY LOSSES; COSTS OR DAMAGES OF ANY KIND INCURRED OR SUFFERED BY YOU AS A RESULT OF SERVICES PROVIDED BY ANY OF THE COMPANY PROVIDERS ACCESSED THROUGH THE SERVICE.

c. YOU REPRESENT THAT YOU HAVE INDEPENDENTLY INVESTIGATED THE ADVISABILITY OF USING THE LOCATION SERVICES MADE AVAILABLE TO YOU BY THE COMPANY AND THE POSSIBLE RISKS INVOLVED IN USING SUCH SERVICES. YOU AGREE TO MAINTAIN YOUR OWN INSURANCE COVERING SUCH RISKS AND WILL LOOK SOLELY TO SUCH INSURANCE FOR REIMBURSEMENT OF ANY RESULTING DAMAGES.

11. Third Party Disputes
THE COMPANY IS NOT AFFILIATED WITH ANY CARRIER, SERVICE PROVIDER, OR THIRD PARTY SERVICE, AND ANY DISPUTE YOU HAVE WITH ANY CARRIER, SERVICE PROVIDER, THIRD PARTY SERVICE OR OTHER THIRD PARTY ARISING FROM YOUR USE OF THE SERVICE, INCLUDING, WITHOUT LIMITATION, ANY OTHER USER OF THE SERVICE OR YOUR EMPLOYER, IS DIRECTLY BETWEEN YOU AND SUCH THIRD PARTY, AND YOU IRREVOCABLY RELEASE THE COMPANY (AND OUR OFFICERS, DIRECTORS, AGENTS, SUBSIDIARIES, JOINT VENTURES, AND EMPLOYEES) FROM ANY AND ALL CLAIMS, DEMANDS AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH DISPUTES.

12. Force Majeure.
THE COMPANY will not be liable for any delay or failure to perform any obligation herein if the delay or failure is due to unforeseen events that are beyond THE COMPANY’s reasonable control, such as strikes, blockade, war, terrorism, riots, natural disasters, epidemic or governmental action, in so far as such an event prevents or delays THE COMPANY in fulfilling its obligations hereunder.

13. Indemnification and Release.
a. You will defend, indemnify and hold THE COMPANY, its licensors and each such party’s parent organizations, subsidiaries, affiliates, officers, directors, members, employees, attorneys and agents, harmless against any loss or damage of any kind (including, without limitation, attorneys’ fees and lost revenues) arising from: (i) any and all breaches by you of this Agreement or any representation, warranty or covenant contained herein; (ii) any and all use of the Service not specifically authorized hereunder and on the Service; and (iii) any and all claims and actions against THE COMPANY by other parties to whom you allow access to the Service.

b. You further waive, release and forever discharge THE COMPANY Parties from any and all responsibility or liability for injuries or damages resulting from your Locations or any other service obtained through the use of the Service, including injuries or damages caused by the negligent act or omission of the Released Parties or in any way arising out of or connected with the Service.

c. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in such case, you agree to cooperate with our defense of such claim. You will not, in any event, settle any claim or matter without our written consent.

14. Additional Service Features.
The Service may contain information on products, and services provided by third parties, including its Providers, and links (including advertisements) to third party web sites. This information and these products, services, and links are provided only as a convenience to users. THE COMPANY does not review or control this information or these products, services, or other web sites, and THE COMPANY does not make any representations or warranties, express or implied, regarding this information or these products, services, or web sites. Inclusion of any of the foregoing in the Service does not constitute or imply an endorsement, authorization, sponsorship, or affiliation by or with THE COMPANY with respect to any third party or its web site or content, or any information, products, or services provided by that third party. THE COMPANY is under no obligation to maintain any link on the Service and may remove a link at any time in its sole discretion for any reason whatsoever.

15. Dispute Resolution.
a. Mandatory Arbitration. Please read this carefully. It affects your rights. YOU AND THE COMPANY AND EACH OF OUR RESPECTIVE CORPORATE PARENTS, SUBSIDIARIES, AFFILIATES, PREDECESSORS IN INTEREST, SUCCESSORS, AND PERMITTED ASSIGNS AGREE TO ARBITRATION (EXCEPT FOR MATTERS THAT MAY BE TAKEN TO SMALL CLAIMS COURT), AS THE EXCLUSIVE FORM OF DISPUTE RESOLUTION EXCEPT AS PROVIDED FOR BELOW, FOR ALL DISPUTES AND CLAIMS ARISING OUT OF OR RELATING TO THIS AGREEMENT OR YOUR USE OF THE SERVICE. Arbitration uses a neutral arbitrator instead of a judge or jury, allows for more limited discovery than in court, and is subject to very limited review by courts. Please visit www.adr.org for more information about arbitration.
i. Commencing Arbitration. A party seeking arbitration must first send to the other, by certified mail, a written notice of intent to arbitrate (a "Notice"), or, in the absence of a mailing address provided by you to THE COMPANY, to you via any other method available to THE COMPANY, including via e-mail. The Notice to THE COMPANY should be addressed to Slimiot Private Limited, 429, Sector 11D, Faridabad, Haryana, India, Attn: Chief Executive Officer (the "Address"). The Notice must (A) describe the nature and basis of the claim or dispute; and (B) set forth the specific relief sought (the "Demand"). If the claim is not resolved within 30 days after the Notice is received, then you or THE COMPANY may commence an arbitration proceeding as set forth below or file a claim in small claims court. INDIAN INSTITUTE OF ARBITRATION AND MEDIATION (IIAM) WILL ADMINISTER ANY ARBITRATION IN ACCORDANCE WITH ITS COMMERCIAL ARBITRATION RULES AND THE SUPPLEMENTARY PROCEDURES FOR CONSUMER RELATED DISPUTES (THE "Rules"), AS MODIFIED BY THIS AGREEMENT. The Rules and IIAM forms are available at https://www.arbitrationindia.com/ If you are required to pay a filing fee to commence arbitration against THE COMPANY, then THE COMPANY will promptly reimburse you for your confirmed payment of the filing fee upon THE COMPANY's receipt of Notice at the Address that you have commenced arbitration along with a receipt for the filing fee, unless your Demand is equal to or greater than INR 50,000 or was filed in bad faith.
ii. Arbitration Proceeding. The arbitration will be in English. A single independent and impartial arbitrator with his or her primary place of business in New Delhi, will be appointed pursuant to the Rules, as modified herein. You and THE COMPANY agree to comply with the following rules, which are intended to streamline the dispute resolution process and reduce the costs and burdens on the parties: (A) the arbitration will be conducted by telephone, online and/or be solely based on written submissions, the specific manner to be chosen by the party initiating the arbitration; (B) the arbitration will not require any personal appearance by the parties or witnesses unless otherwise mutually agreed in writing by the parties; and (C) any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.
iii. No Class Actions. YOU AND THE COMPANY AGREE THAT YOU AND THE COMPANY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. FURTHER, YOU AGREE THAT THE ARBITRATOR MAY NOT CONSOLIDATE PROCEEDINGS OF MORE THAN ONE PERSON’S CLAIMS, AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING, AND THAT IF THIS SPECIFIC PROVISO IS FOUND TO BE UNENFORCEABLE, THEN THIS ENTIRE MANDATORY ARBITRATION SECTION WILL BE NULL AND VOID.
iv. Decision of the Arbitrator. Barring extraordinary circumstances, the arbitrator will issue his or her decision within 120 days from the date the arbitrator is appointed. The arbitrator may extend this deadline by 30 days in the interests of justice. Arbitration proceedings will be closed to the public and confidential, and all related records will be permanently sealed, except as necessary to obtain court confirmation of the award. The award will be in writing and will include a statement setting forth the reasons for the claim’s disposition. The arbitrator will apply Indian law during the arbitration. You agree that these terms and your use of the App evidences a transaction involving interstate commerce.
b. Equitable Relief. The foregoing provisions of this Section 15 do not apply to any claim in which THE COMPANY seeks equitable relief of any kind. You acknowledge that, in the event of a breach of this Agreement by THE COMPANY or any third party, the damage or harm, if any, caused to you will not entitle you to seek injunctive or other equitable relief against THE COMPANY, and your only remedy will be for monetary damages, subject to the limitations of liability set forth above.
c. Claims. You and THE COMPANY agree that, notwithstanding any other rights the party may have under law or equity, any cause of action arising out of or related to this Agreement or the Service, excluding a claim for indemnification, must commence within one year after the cause of action accrues. Otherwise, such cause of action is permanently barred.
d. Improperly Filed Claims. All claims you bring against THE COMPANY must be resolved in accordance with this Section 15. All claims filed or brought contrary to this Section 15 will be considered improperly filed. Should you file a claim contrary to this Section 15, THE COMPANY may recover attorneys’ fees and costs up to INR 300,000, provided that THE COMPANY has notified you in writing of the improperly filed claim, and you have failed to promptly withdraw the claim.
e. Modifications. If THE COMPANY changes the Mandatory Arbitration provision (other than a change to THE COMPANY’s Address), then you may reject any such change by sending us written notice to THE COMPANY’s Address within 30 days of the change, in which case your Account and your right to use the Service will terminate immediately, and this Section 19, as in effect immediately prior to the amendments you reject, will survive termination of this Agreement.
f. Enforceability. If only Section 15.a.iii or the entirety of this Section 15 is found to be unenforceable, then the entirety of this Section 15 will be null and void and, in such case, the parties agree that the exclusive jurisdiction and venue described in Section 16 will govern any action arising out of or related to this Agreement.

16. Governing Law; Choice of Forum.
The laws of the State of New Delhi, excluding its conflicts of law rules, govern this Agreement and your use of the Service. Your use of the Service may also be subject to other local, state, national, or international laws; provided, however, that the United Nations Convention on Contracts for the International Sale of Goods will not apply to any provision of this Agreement. To the extent that any action relating to any dispute hereunder is permitted to be brought in a court of law, such action will be subject to the exclusive jurisdiction of the state and federal courts located in New Delhi and you hereby irrevocably submit to personal jurisdiction in such courts, and waive any defense of inconvenient forum.

17. Feedback.
While our staff continually works to develop and evaluate our own product ideas and features, we pride ourselves on paying close attention to the interests, feedback, comments, and suggestions we receive from our Users. If you send us or our employees any ideas or suggestions for products, services, features, modifications, enhancements, content, promotions, strategies, or product/feature names, or any related materials (collectively “Feedback”), then regardless of what your communication may say, the following terms apply, to avoid future misunderstandings. By sending us Feedback, you agree that:

a. THE COMPANY will own, exclusively, all known or later discovered rights to the Feedback;

b. THE COMPANY will not be subject to any obligation of confidentiality and will not be liable for any use or disclosure of any Feedback; and

c. THE COMPANY will be entitled to unrestricted use of the Feedback for any purpose whatsoever, commercial or otherwise, without compensation to you or any other person.

18. Entire Agreement; Variation.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

19. Severability.
If any provision of this Agreement is held invalid, illegal or unenforceable, such provisions will be modified, or if not possible, severed, to reflect the fullest valid, legal and enforceable expression of the intent of the parties and the remainder of this Agreement will not be affected thereby.
20. Relationship of Parties.
Nothing herein will be deemed to create an employer- employee relationship between THE COMPANY and you, nor any agency, joint venture or partnership relationship between the parties. Neither party will have the right to bind the other to any obligation, nor have the right to incur any liability on behalf of the other.
21. Waiver.
No delay, omission, or failure to exercise any right or remedy provided herein will be deemed to be a waiver thereof or an acquiescence in the event giving rise to such right or remedy, but every such right or remedy may be exercised, from time to time as may be deemed expedient by the party exercising such remedy or right.

22. Assignment.
Neither this Agreement nor any of the rights granted to you herein may be assigned or transferred by you, whether voluntarily or by operation of law, without the express prior written permission of THE COMPANY and any attempt to do so will be null and void. However, THE COMPANY may assign or transfer this Agreement at any time without your permission.

23. Third-Party Beneficiaries.
The provisions of this Agreement relating to the rights of THE COMPANY’s Content Providers are intended for the benefit of such Content Providers, and such Content Providers, as third-party beneficiaries, will be entitled to enforce such provisions in accordance with their terms, irrespective of the fact that they are not signatories to this Agreement.`;

export const PRIVACY_POLICY = `This Privacy Policy applies to users of the SLIMiot™ products and applications. Slimiot Private Limited, an Indian company, is the developer and the owner of all the commercial rights to the applications and products sold under the SLIMiot™ Brand. This includes Slimring, Dozemate, Hexaskin, Slimiot walk, Slimiot PPG, Slimiot ECG, Slimiot HRV and others.

Slimiot Private Limited ("We", "Our", "SLIMiot" or "The Company") have updated our privacy policy to include additional information required under applicable Data protection regulations as the following:

Why we process personal data
Legal grounds for processing personal data
Contact information for SLIMiot data controllers
Contact information for the SLIMiot data protection officer in India
Categories of Personal Data Processed by SLIMiot
Personal data that is processed when you create a SLIMiot account:
When you create a SLIMiot account, we ask you to provide your email address and name. You can choose to provide only your first name or a nickname instead of your full name if you wish.

Purposes and legal Grounds:
(a) SLIMiot processes your email address because you use your email address and your password to sign in to your account. The legal ground for processing your email address for this purpose is based on SLIMiot’s legitimate interest in protecting the security of your account.
(b) SLIMiot also processes your email address for the purpose of sending you important information about your SLIMiot products, apps or account, such as important safety information or material changes to this Privacy Policy. The name you provide is associated with your account profile, and is displayed when you submit comments or other material on a SLIMiot website or app. The legal ground for processing your email address and name for these purposes is SLIMiot’s legitimate interest in providing you important safety or other information about your SLIMiot products, apps or account or material changes to this Privacy Policy, and in providing you an opportunity to engage with other SLIMiot users.
(c) If you provide your opt-in consent to receiving marketing information from SLIMiot, SLIMiot will also process your email address for the purpose of sending you marketing information about SLIMiot products and apps. The legal ground for processing your email address for this purpose is your consent. You may withdraw your consent at any time by changing your preferences in your SLIMiot account or through the unsubscribe link at the bottom of our marketing emails. The marketing emails you receive from SLIMiot are based on the preferences you provide in your SLIMiot account, the locale indicated by your Internet Protocol (IP) address, the types of SLIMiot devices you have added to your SLIMiot account, and any subscriptions included in your SLIMiot account. The legal ground for processing this data for this purpose is SLIMiot’s legitimate interest in reducing the number of marketing emails sent to each particular customer by selecting which customers receive a particular marketing email rather than sending every marketing email to every customer who has consented to receiving marketing emails.
(d) SLIMiot also processes your email address to associate it with your SLIMiot account when you interact with our customer support representatives. The legal ground for this processing is our legitimate interest in providing quality customer support.
Personal data that is processed when you sign in to your SLIMiot account with Social Media Credentials if you choose:
You may choose to sign in to your SLIMiot account using your social media sign in credentials (e.g., your Facebook sign in credentials). If you choose to do this, the first time you do so you will be asked whether you agree that the social media provider may provide certain information to SLIMiot, such as your name, email address, profile photo, posts, comments and other information associated with your social media account.
All of this information is made available to SLIMiot by the social media provider due to the way the social sign-on configuration works. However, the only information SLIMiot retains and processes is your email address. If you do not want your information to be shared with SLIMiot by the social media provider, then you can simply sign in to your SLIMiot account using your SLIMiot account credentials instead of your social media account credentials.
Purposes and legal Grounds:
SLIMiot associates the email address provided by the social media provider with your SLIMiot account so that you can use your email address to sign in to your SLIMiot account in the future if you no longer wish to sign in using your social media account credentials. The legal ground for processing this information for this purpose is SLIMiot’s legitimate interest in providing you an alternative sign in method and in securing your account.
Personal data that is processed when you sync your SLIMiot device:
When you sync your device, we log data about the transmission, such as the IP address used when syncing, the sync time and date, crash/diagnostic logs, geographic location of the device, information about your device, information about the network used to sync (e.g., Wi-Fi or cellular) and device battery level.
Purposes and legal Grounds:
We process this information to help identify and resolve errors or syncing issues. The legal ground for processing this information for this purpose is SLIMiot’s legitimate interest in resolving errors or syncing issues and providing quality product support.
Personal data that is processed when you communicate with SLIMiot:
When you interact with our customer support representatives via email, telephone, online or in person, we collect personal data, such as your name, mailing address, phone number, email address and contact preferences; and information about the SLIMiot products you own, such as their device ID and date of purchase. We also may create event logs that are useful in diagnosing product or app performance-related issues, and capture information relating to the support or service issue. To improve customer service, subject to applicable laws, we may also record and review conversations with customer support representatives, and analyze any feedback provided to us through voluntary customer surveys. With your consent, our customer support representatives may sign in to your SLIMiot account, if appropriate, to help troubleshoot and resolve your issue.
Purposes and legal Grounds:
We use this information to provide you with customer and product support and to monitor the quality and types of customer and product support we provide to our customers. The legal ground for processing this information for these purposes is SLIMiot’s legitimate interests in providing quality product support. The legal ground for signing in to your SLIMiot account, if appropriate, to help troubleshoot and resolve your issue is consent, which you may withdraw.

Personal data that is processed when you use your SLIMiot auto navigation device or app:

If you use a SLIMiot device or app and provide your consent, then SLIMiot will collect and upload from your device data such as location, speed, direction, and time and date of recording. If you provide your consent when asked, then SLIMiot may also share this aggregated data with or sell this data to third parties to enhance the quality of the traffic, parking and other features enabled by content providers.
Purposes and legal Grounds:
This data is aggregated with data from other consenting users and is used to enhance the quality of our products and apps and the traffic, parking and other features enabled by SLIMiot or third parties. The legal ground for processing this data for this purpose is consent, which you may withdraw at any time within the settings of your SLIMiot device or app.
Personal data that is processed when you purchase a product on a SLIMiot website:
If you purchase a product on a SLIMiot website, then SLIMiot will collect your name, mailing address and telephone number. We do not view or store your payment card information a third party.

Purposes and legal Grounds:
We collect your name, mailing address and telephone number so we can process your order and fulfill your purchase. The legal ground for processing your name, mailing address and telephone number for these purposes is performance of a contract. We also process your personal data as part of our fraud detection processes. The legal ground for processing your personal data for that purpose is our legitimate interest in protecting SLIMiot and our customers from attempts to engage in fraudulent transactions.
Categories of Recipients of Personal Data
Your friends invitees:
Friends is a feature available on some SLIMiot devices that enables you to send a link to people of your choice that allows them to see the real-time location of your device. Because anyone with access to the link will be able to see the real-time location of your SLIMiot device, you should use caution in determining to whom you want to send the link and be sure that you trust them to not send the link to others whom you do not want to be able to view the location of your SLIMiot device.

Other service providers:
SLIMiot uses cloud services from third parties to assist in sending emails. Those services track the activities associated with these emails, such as whether they were opened, whether links in the emails were clicked on, and whether purchases were made following clicks on those links. SLIMiot uses this data to analyze the level of engagement with its emails. SLIMiot uses third-party service providers to ship purchased products to customers and to help us better understand our customers needs.

Other disclosures:
We may disclose personal data about you to others: 

(a) if we have your valid consent to do so; 

(b) to comply with a valid subpoena, legal order, court order, legal process, or other legal obligation; 

(c) to enforce any of our terms and conditions or policies; or 

(d) as necessary to pursue available legal remedies or defend legal claims. We may also transfer your personal data to an affiliate, a subsidiary or a third party in the event of any reorganization, merger, sale, joint venture, assignment, transfer or other disposition of all or any portion of SLIMiot’s business, assets or stock, including, without limitation, in connection with any bankruptcy or similar proceeding, provided that any such entity that we transfer personal data to will not be permitted to process your personal data other than as described in this Privacy Policy without providing you notice and, if required by applicable laws, obtaining your consent.

Transfers of Personal Data
SLIMiot is a global business. To offer our products, apps and services, we may need to transfer your personal data to other SLIMiot companies in other countries. When you create a SLIMiot account, add personal data in your account profile, or upload data to your SLIMiot account, your personal data will be collected and stored on SLIMiot servers in India, United States or in Europe, as configured per your SLIMiot device. Personal data regarding individuals who reside in a country in the Asia, European Economic Area or USA is controlled by SLIMiot's Affiliate and processed on its behalf by Slimiot Private Limited.
Any transfers of personal data from SLIMiot companies are done pursuant to Integrity and approved Model Contractual Clauses.
All SLIMiot companies are required to follow the privacy practices set forth in this Privacy Statement.

Cookies and Similar Technologies
Websites:
To help analyze how you and other visitors navigate SLIMiot websites, and compile aggregate statistics about site usage and response rates, we, with assistance from third-party analytics service providers, collect certain information when you visit our site. This information includes IP address, geographic location of the device, browser type, browser language, date and time of your request, time(s) of your visit(s), page views and page elements (e.g., links) that you click. We may use cookies, pixel tags, web beacons, clear GIFs or other similar tools on our site or in our email messages to assist us in collecting and analyzing such information. We use this information to provide better, more relevant content on our site, to measure the effectiveness of advertisements, to identify and fix problems, and to improve your overall experience on our site. We may also engage one or more third-party service providers to provide online advertisements on our behalf. They may use a pixel tag or other similar technology to collect information about your visits to sites, and they may use that information to send you targeted advertisements.
If you do not want information collected through the use of these technologies, there is a simple procedure in most browsers that allows you to automatically decline many of these technologies, or to be given the choice of declining or accepting them.
If you reside in the Indian sub continent, European Union or other jurisdiction that requires us to obtain your consent to use cookies on our sites, then you will have an opportunity to manage your cookie preferences on the sites; except that certain cookies are required to enable core site functionality, and you cannot choose to disable those cookies.

SLIMiot Mobile apps:
We also collect data from users about their usage of SLIMiot mobile apps. The types of analytical information that are collected include the date and time the app accesses our servers, app version, the location of the device, language setting, what information and files have been downloaded to the app, user behavior (e.g., features used, frequency of use), device state information, device model, hardware and operating system information, and information relating to how the app functions. SLIMiot uses this data to improve the quality and functionality of our mobile apps, to develop and market products and features that best serve you and other users; and to help identify and fix app stability issues and other usability problems as quickly as possible.
The legal ground for processing this analytical information is our legitimate interest in understanding how our customers interact with our products, apps and websites so we can enhance the user experience and functionality of our products, apps and websites.
Here are examples of third-party providers of analytics and similar services we currently use:

Cookies and Similar Technologies
Google: Google Analytics is used to track site statistics and user demographics, interests and behavior on websites. We also use Google Search Console to help understand how our website visitors find our website and to improve our search engine optimization. Find out more information about how this analytics information may be used, how to control the use of your information, and how to opt-out of having your data used by Google Analytics.
Application Performance Monitoring:
SLIMiot uses various software tools to analyze and monitor the performance of our complex ecosystem. To provide such services, our app receives basic request information, including IP address, necessary to detect and diagnose anomalous errors and response times.

Social Networks:
Third-party social networks that provide interactive plug-ins or social networking features (e.g., to allow you to connect to Facebook or Google to find friends to add as connections or to “Like” a page) on SLIMiot websites or mobile apps, may use cookies or other methods (e.g., web beacons) to gather information regarding your use of our websites and apps. The use of such information by a third party depends on the privacy policy available on that social network’s website, which we encourage you to carefully review. Such third parties may use these cookies or other tracking methods for their own purposes by relating information about your use of our site with any of your Personal Information that they may have. We may also obtain analytics information from social networks that help us measure the effectiveness of our content and advertisements on social networks (e.g., impressions and clicks).

Children
The SLIMiot device is not intended to be purchased by anyone under the age of 13 years old. When a parent and or legal guardian purchases a device for use by a child and to locate a child the parent is acknowledging that any personal information transmitted to SLIMiot is solely the parents and not that of a child under the age of 13. We do not knowingly collect personal information from children under 13 years of age. If we learn that we have collected personal information from a child under age 13, we will delete that information as quickly as possible. If you believe that we might have any information from a child under age 13, please contact us through support@SLIMiot.com

Privacy Policy Updates
We may update this Privacy Policy from time to time as we add new products and apps, as we improve our current offerings and as technologies and laws change. You can determine when this Privacy Policy was last revised by referring to the “Last updated” legend at the top of this page. Any changes will become effective upon our posting of the revised Privacy Policy.
We will provide notice to you if these changes are material and, where required by applicable law, we will obtain your consent. This notice will be provided by email or by posting notice of the changes on the SLIMiot websites and apps that link to this Privacy Policy.

Retention of Personal Data
We will retain your personal data as long as your SLIMiot account is considered to be active. In addition, see below under “Your Rights” for a description of your right of erasure.

Data Controller and Data Protection Officer
If you reside in a country in the Indian sub continent, European Economic Area or USA, then your personal data collected by SLIMiot is controlled by Slimiot Private Limited India, which is located within the office of 429, Sector 11D, Faridabad, Haryana, India.

Your Rights
You have the right under the General Data Protection Regulation to request from SLIMiot access to and rectification or erasure of your personal data, data portability, restriction of processing of your personal data, the right to object to processing of your personal data, and the right to lodge a complaint with a supervisory authority.
To request access to or rectification, portability or erasure of your personal data, or to delete your SLIMiot account, write your request by email to info@slimiot.com and make sure to include all the details about your SLIMiot account such as the log-in email and the device ID(s) of your SLIMiot devices.
If you wish to exercise your right to restriction of processing or your right to object to processing, contact SLIMiot's Data Protection Officer at info@slimiot.com`;